### ISSUE TITLE
ipsw-dl needs some fixes

### ISSUE THREAD

**Issue by Merculous** [matteyeux/ios-tools#1]
Sometimes it does not parse correct iOS versions. E.g when trying to download for iPhone2,1 5.1.1 it does not parse as "5.1.1" but instead it downloads "5.1." Also, as another example, I randomly entered "iPhone 3,1 7.0.6" it starts to download 7.0.4....

**Comment by Merculous** [comment]
Also, iPhone4,1 trying to download "5.0.1" will actually download the correct ipsw, but when trying to download "5.0" : 
Traceback (most recent call last):
  File "ipsw-dl.py", line 84, in <module>
    parse_json(device, version)
  File "ipsw-dl.py", line 53, in parse_json
    buildid = data["firmwares"][i]["buildid"]
IndexError: list index out of range

**Comment by matteyeux** [comment]
Hey thanks for reporting this issue.
It may be a issue with ipsw.me's json file. I'll investigate to confirm this issue.

**Comment by matteyeux** [comment]
Issue should be fixed now.
